# Generated by Django 3.2 on 2021-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_irpf', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ClientConfiguration',
                'verbose_name_plural': 'ClientConfigurations',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('additinal_info', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['-pk'],
            },
        ),
    ]
