# Generated by Django 3.2 on 2021-04-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cif', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(db_column='postalCode', max_length=5)),
                ('invoice_code', models.CharField(db_column='invoiceCode', max_length=3, unique=True)),
                ('invoice_index', models.IntegerField(db_column='invoiceIndex')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Documents Type',
                'db_table': 'documentType',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
    ]
