# Generated by Django 3.2 on 2021-05-01 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Documents Type',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('cif', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(db_column='postalCode', max_length=5)),
                ('invoice_code', models.CharField(db_column='invoiceCode', max_length=3, unique=True)),
                ('invoice_index', models.IntegerField(db_column='invoiceIndex')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.ForeignKey(db_column='documentType', on_delete=django.db.models.deletion.DO_NOTHING, to='client.documenttype')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-name'],
            },
        ),
    ]
