# Generated by Django 3.2 on 2021-04-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': True, 'ordering': ['-name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
