# Generated by Django 3.2 on 2021-04-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False, 'ordering': ['-name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
