# Generated by Django 3.2 on 2021-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'verbose_name': 'Invoice Line', 'verbose_name_plural': 'Invoice Lines'},
        ),
    ]
